apiVersion: k1.kubefirst.io/v1beta1
kind: Watcher
metadata:
  name: wait-app-02
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync    
spec:
    exit: 0
    timeout: 300
    pods:
      - name: my-app-02
        namespace:  default
        phase: Running      
        apiVersion: v1
        kind: Pod    
    jobs:
      - name: run-some-long-action-app2
        namespace:  argocd
        succeeded: 1
---
apiVersion: v1
kind: Pod
metadata:
  name:  my-app-03
  namespace:  default
spec:
  containers:
# Image needs to come from install ECR not github, I believe...
   -  image: 6zar/k1test:latest
      name: k1-ready
      command: ["tail"]
      args: ["-f","/dev/null"]  
