apiVersion: k1.kubefirst.io/v1beta1
kind: Watcher
metadata:
  name: wait-app-02
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync    
spec:
    exit: 0
    timeout: 300
    pods:
      - name: my-app-02
        namespace:  default
        phase: Running      
        apiVersion: v1
        kind: Pod    
    jobs:
      - name: run-some-long-action-app2
        namespace:  argocd
        succeeded: 1
---
apiVersion: v1
kind: Pod
metadata:
  name:  my-app-03
  namespace:  default
spec:
  containers:
# Image needs to come from install ECR not github, I believe...
   -  image: 6zar/k1test:latest
      name: k1-ready
      command: ["tail"]
      args: ["-f","/dev/null"]  
---
apiVersion: batch/v1
kind: Job
metadata:
  name: run-some-long-action-app3
  namespace: argocd
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: c
          image: alpine:latest
          command:
            - sh
            - -c
          args:
            - "apk add curl && curl -H \"Content-type: application/json; charset=utf-8\" --data
              '{\"channel\":\"test\",\"blocks\":[{\"type\":\"section\",\"text\"\
              :{\"type\":\"mrkdwn\",\"text\":\"The APP2 is up and
              running!\"}}]}' -H \"Authorization: Bearer $MYSECRETPASSWORD\" -X
              POST https://slack.com/api/chat.postMessage"
          env:
            - name: MYSECRETPASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-notifications-secret
                  key: slack-token
      restartPolicy: Never
  backoffLimit: 1
