apiVersion: k1.kubefirst.io/v1beta1
kind: Watcher
metadata:
  name: wait-app-01
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync    
spec:
    exit: 0
    timeout: 300
    pods:
      - name: my-app-01-a
        namespace:  default
        phase: Running      
        apiVersion: v1
        kind: Pod    
        
--- 
apiVersion: v1
kind: Pod
metadata:
  name:  my-app-02
  namespace:  default
spec:
  containers:
# Image needs to come from install ECR not github, I believe...
   -  image: 6zar/k1test:latest
      name: k1-ready
      command: ["tail"]
      args: ["-f","/dev/null"]  
--- 
# Creates the argo annotation for CRD
apiVersion: batch/v1
kind: Job
metadata:
  name: run-some-long-action-app2
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: test
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: c
        image: portainer/kubectl-shell:latest
        command:
        - /bin/sh
        - -c
        - |
          #Do something          
          sleep 30
      restartPolicy: Never
  backoffLimit: 1   
