apiVersion: k1.kubefirst.io/v1beta1
kind: Watcher
metadata:
  name: wait-app-01
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync    
spec:
    exit: 0
    timeout: 300
    pods:
      - name: my-app-01-a
        namespace:  default
        phase: Running      
        apiVersion: v1
        kind: Pod    
        
--- 
apiVersion: v1
kind: Pod
metadata:
  name:  my-app-02
  namespace:  default
spec:
  containers:
# Image needs to come from install ECR not github, I believe...
   -  image: 6zar/k1test:latest
      name: k1-ready
      command: ["tail"]
      args: ["-f","/dev/null"]  
--- 
# Creates the argo annotation for CRD
apiVersion: batch/v1
kind: Job
metadata:
  name: run-some-long-action-app2
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: test
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: c
        image: golang:latest
        command:
        - curl -H "Content-type: application/json" \
          --data '{"channel":"test","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"The APP1 is up and running!"}}]}' \
          -H "Authorization: Bearer xoxb-4584846825269-4590265148820-7ptfTSs8TL4PIPD67k8CL4X1" \
          -X POST https://slack.com/api/chat.postMessage
      restartPolicy: Never
  backoffLimit: 1   
